"""Read project .env and generate firmware/src/wifi_config.h before build."""

from __future__ import annotations

import re
from pathlib import Path

Import("env")  # type: ignore[name-defined]  # noqa: F821

PROJECT_DIR = Path(env["PROJECT_DIR"])  # type: ignore[name-defined]  # noqa: F821
ROOT_DIR = PROJECT_DIR.parent
ENV_FILE = ROOT_DIR / ".env"
OUTPUT = PROJECT_DIR / "src" / "wifi_config.h"
DEFAULT_HOSTNAME = "esp32-pc-monitor"
DEFAULT_PORT = 5000


def parse_env(path: Path) -> dict[str, str]:
    values: dict[str, str] = {}
    if not path.exists():
        return values

    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        values[key.strip()] = value.strip().strip('"').strip("'")
    return values


def c_escape(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"')


def valid_hostname(value: str) -> str:
    cleaned = value.strip().lower()
    if not re.fullmatch(r"[a-z0-9-]+", cleaned):
        raise ValueError(f"Invalid DEVICE_HOSTNAME: {value!r}")
    return cleaned


env_values = parse_env(ENV_FILE)
ssid = env_values.get("WIFI_SSID", "").strip()
password = env_values.get("WIFI_PASSWORD", "").strip()
hostname = valid_hostname(env_values.get("DEVICE_HOSTNAME", DEFAULT_HOSTNAME))
port = int(env_values.get("STATS_PORT", str(DEFAULT_PORT)))
wifi_enabled = bool(ssid and password)

header = f"""#pragma once
/* Generated by scripts/generate_wifi_config.py — do not edit. */

#define WIFI_ENABLED {1 if wifi_enabled else 0}
#define WIFI_SSID "{c_escape(ssid)}"
#define WIFI_PASSWORD "{c_escape(password)}"
#define DEVICE_HOSTNAME "{c_escape(hostname)}"
#define STATS_TCP_PORT {port}
"""

OUTPUT.write_text(header, encoding="utf-8")

if wifi_enabled:
    print(f"[wifi] Enabled: hostname={hostname}.local port={port}")
else:
    print("[wifi] Disabled: create .env from .env.example with WIFI_SSID and WIFI_PASSWORD")

env.Append(CPPDEFINES=[("WIFI_ENABLED", 1 if wifi_enabled else 0)])  # type: ignore[name-defined]  # noqa: F821
